# MMP""MM""YMM               .M"""bgd
# P'   MM   `7              ,MI    "Y
#      MM  .gP"Ya   ,6"Yb.  `MMb.   `7MMpdMAo.  ,pW"Wq.   ,pW"Wq.`7MMpMMMb.
#      MM ,M'   Yb 8)   MM    `YMMNq. MM   `Wb 6W'   `Wb 6W'   `Wb MM    MM
#      MM 8M""""""  ,pm9MM  .     `MM MM    M8 8M     M8 8M     M8 MM    MM
#      MM YM.    , 8M   MM  Mb     dM MM   ,AP YA.   ,A9 YA.   ,A9 MM    MM
#    .JMML.`Mbmmd' `Moo9^Yo.P"Ybmmd"  MMbmmd'   `Ybmd9'   `Ybmd9'.JMML  JMML.
#                                     MM
#                                   .JMML.
# TeaSpoon Configuration File

# Config Version Number [DO-NOT-MODIFY]
version: 29

entities:
 # Weather to register Vanilla Entities (Set to false if you're going to use a MobAI Plugin such as, PureEntitiesX etc...) or not
 register: true
 # Enable Lightning Fire & Damage
 lightningFire: true
 # Enable EndCrystal Explosion
 endCrystalExplosion: true
 # EndCrystal Explosion Power
 endCrystalPower: 6
 creeper:
  # Enable creepers' ability to explode
  enableExplosions: false  # disabled by default. Nobody wants griefed servers ¯\_(ツ)_/¯
  # Enable Charged Creepers when hit by lightning
  enableChargedCreepers: true
  # Enable Ignited Creepers when clicked by Flint and Steel (if Explosions are disabled, it will only despawn)
  enableIgnitedCreepers: true
 snowGolem:
  # Enable the ability to shear Snow Golems (Currently Doesn't work. idk why. maybe PC Docs isn't consistent with PE?)
  shearable: true
  # Enable to let snow golems leave out traces of snow (If disabled, The client will still show snow trails)
  generatesSnow: false # Disabled by default (might be used to griefed servers :/)
  # Enable to let snow golems melt when in hot biomes, in contact with raining / water (RIP Snowman#1337 2018-2018 ;-;)
  melting: true

enchantments:
 # Weather to enable & register Vanilla Enchantments (Set to false if you're going to use VanillaEnchantments plugin etc...) or not
 register: true
 enchantingTableEnabled: true

dimensions:
 # Enable / Disable Dimensions
 enable: true
 nether:
  levelName: "teanether"
  # Vanilla-Like Nether Tranfer is not perfect and would take more time (possibly lag)...
  vanillaNetherTranfer: false
 end:
  levelName: "ender"
 # SET TO BLANK ("") TO DISABLE
 overrideOverworldLevel: ""

misc:
 # Enable to generate new Fishing LootTables everyday
 randomFishingLootTables: false
 # Minecart! We have 2 minecart,
 # Broken ones = false      More fun, trust me ;)
 # Vanilla ones = true      Classic minecart behaviour
 # Set it to 'none' if you don't want to use them
 vanilla-minecarts: 'false'
 # Toggle Lightning Rods (BlazeRods)
 lightningRods: false
 
enderPearl:
 enable: true
 cooldown: 2
 damage: 5

chorusFruit:
 enable: true
 cooldown: 2

weather: 
 enable: true
 # Minimum Weather Duration (IN TICKS)
 minDuration: 6000
 # Maximum Weather Duration (IN TICKS)
 maxDuration: 12000
 # If lightning should be spawned in stormy weather
 lightning: true

player:
 # Enable to dis-allow container interactions & item dropping when in creative
 limitedCreative: false
 # In vanilla, this is false... In Genisys, its true
 clearInventoryOnGameModeChange: false
 instantArmor:
  enable: true
 # Toggle to replace current armor or not (Vanilla-Way: false) [might cause glitches/bugs on server lag]
  replace: false
 # Elytra configuration
 elytra:
  enable: true
  enableElytraBoost: true
  elytraBoostParticles: true
 fishing: true

mobSpawner:
 enable: true
 # Drop spawners on silk touch (damageAsEID needs to be enabled)
 silkTouchSpawners: false
 # Use MonsterSpawner Damage Value as the Entity ID -- False in vanilla minecraft
 damageAsEID: false

fireworks:
 enable: true

Xp:
 dropMobExperience: true

blocks:
 dragonEggTeleport: true
 brewingStands: true
 enableIronGolem: true
 enableSnowGolem: true
 snowLayerMelts: true

hopper:
 itemTransferEnable: true

beacon:
 # You can only disable effects (if it has any effect at all) because beacons are rendered client-side
 enable: true
 effectsEnabled: true

shulkerBox:
 enable: true

anvil:
 enable: true
